spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 비밀번호
    url: jdbc:mariadb://RDS주소:3306/project2
    username: 아이디
  mail:
    host: smtp.gmail.com
    password: 메일비밀번호
    username: ddogi94@gmail.com
    port: 465
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          ssl:
            enable: true
    
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true

  data:
   redis:
    host: 13.209.229.66
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

gpt:
  key: GPT 키
