spring:
  profiles:
    active: dev 
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      max-lifetime: 177000 #177초 hikari는  wait_timeout  180 보다 2~3초 정도 짧게 줄것을 권장
  servlet:
    multipart:
      max-file-size: 2MB
            
logging:
  level:
    com:
      green:
        nowon: debug
      amazonaws:
        util:
          EC2MetadataUtils: error
          

---
#application-dev.yml 개발용
spring:
  config:
    activate: 
      on-profile: dev
    import: optional:configserver:http://43.200.239.80:8888
    
---
#application-proc.yml 배포용
spring:
  config:
    activate:
      on-profile: proc
    import: optional:configserver:http://localhost:8888
